version: '3'

services:
  portainer:
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      portainer_network:
        ipv4_address: 172.18.0.2

  nginx:
    container_name: portainer_nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      portainer_network:
        ipv4_address: 172.18.0.3

volumes:
  portainer_data:

networks:
  portainer_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
