version: '3'

services:
  portainer:
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
