version: "3.7"

services:
  portainer:
    container_name: portainer
    environment:
      - TZ=${TZ}
    image: portainer/portainer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.custom.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.custom.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.custom.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.custom.headers.frameDeny=true"
      - "traefik.http.middlewares.custom.headers.sslredirect=true"
      - "traefik.http.middlewares.custom.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.custom.headers.stsPreload=true"
      - "traefik.http.middlewares.custom.headers.stsSeconds=315360000"
    networks:
      - traefik_proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

volumes:
  data:

networks:
  traefik_proxy:
    external: true
